version: 1
disable_existing_loggers: "false"
formatters:
  simple:
    format: "%(levelname)s: %(message)s" # Check format options in documentation
  detailed:
    format: "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  stderr:
    class: loggging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: name-of-log.log # Edit when made
    maxBytes: 10000000 # Check if want more - currently 10 MB
    backupCount: 3 # Check if want more
loggers:
  root:
    level: DEBUG
    handlers:
    - stderr
