email:
  # Must be a list, recipients of email; you should ADD to this.
  recipients:
    - hgsc-submit@hgsc.bcm.edu
  # Where the email is coming from; should be the "owner" of the app.
  sender: hgsc-submit@hgsc.bcm.edu

destination:
  gcp:
    bucket_name: some-bucket

working_dir: some-dir
